### PR TITLE
Fix regex check for column name

### PR DESCRIPTION
**Pull request by sicarul**
The current regex check fails for single-character columns (I created a tap with a variable called "X"), please review at your earliest convenience, thanks!

### CODE REVIEW

**Comment by awm33** [comment]
Hi @sicarul ! Thanks for contributing!

Can you add a test for a single character column? I think since it's not a very common case, if that test isn't there, a regression may happen.

**Comment by sicarul** [comment]
@awm33 sorry, just saw your comment, will get to it

**Comment by sicarul** [comment]
@awm33 I've added the test, however i am not able to get almost any tests passing, most fail for me, including the one i added, i'm not sure what's going on.

**Comment by sicarul** [comment]
Sorry i'll have to open a new PR to switch out the branch, my bad
Created #29

**Pull request closed without merging**
